#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output LVDS-1 --off --output VGA-1 --auto --primary &

wmname LG3D &
vmware-user-suid-wrapper &

bspc monitor VGA-1 -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config normal_border_color "#2FAF2F"
bspc config focused_border_color "#00FF41"
bspc config presel_feedback_color "#00FF41"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill ~/Wallpapers/kaliskull.png &
~/.config/polybar/./launch.sh --shapes &
picom --config ~/.config/picom/picom.conf &
# wal -R

# Matrix polybar
~/.config/polybar/launch.sh &

